# Generated by Django 5.1.4 on 2024-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-27 00:00:00'),
            preserve_default=False,
        ),
    ]
